version: '3.1'

services:
  dilim:
    build: .
    container_name: dilim
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    restart: always
    networks:
      - app-network
  postgresdb:
    image: postgres:13-alpine
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fresh
      POSTGRES_DB: dilim
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge